# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '20 Hours' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20 Hours

  
  pod 'RealmSwift'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'MBCircularProgressBar'
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'
  pod 'AlamofireImage', '~> 2.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 1.0'
  pod 'LTMorphingLabel'
  pod 'YouTubePlayer'
  pod 'DropDown'
  pod 'RKDropdownAlert'
  pod 'Material', '~> 1.0'


end
